//! GitHub App Manifest flow (ADR-0008 §B) — the reproducible, near-zero-touch way to create the
//! trusted-writer App.
//!
//! GitHub has **no API** to create or install an App (a deliberate privilege boundary). The
//! manifest flow is the sanctioned path: we generate a deterministic manifest, a browser submits
//! it to `https://github.com/organizations/{org}/settings/apps/new` (the one consent step GitHub
//! mandates — driven headlessly by the playwright approver in `scripts/bootstrap/`), and GitHub
//! redirects back with a one-time `code` (valid ≤1h) that converts via
//! `POST /app-manifests/{code}/conversions` into `{id, pem, webhook_secret}`. Those are sealed
//! into envctl's vault; the App process holds none of them directly.
//!
//! This module is **pure**: manifest construction, the org create URL, conversion-response
//! parsing, and the install URL — all unit-tested. The browser drive, the conversion POST, and
//! vault sealing are I/O and live in `app-cli` (`fxapp register`).

use serde::Deserialize;
use serde_json::{json, Value};

/// One requested permission (least-privilege; mirrors the App's runtime needs).
/// `access` is GitHub's vocabulary: `"read"`, `"write"`, or `"admin"`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestPermission {
    pub name: String,
    pub access: String,
}

impl ManifestPermission {
    fn new(name: &str, access: &str) -> Self {
        Self {
            name: name.to_string(),
            access: access.to_string(),
        }
    }
}

/// The inputs that fully determine a GitHub App manifest. Deterministic: same config ⇒ same
/// manifest, so re-running the bootstrap reproduces the exact App configuration.
#[derive(Debug, Clone)]
pub struct ManifestConfig {
    pub name: String,
    pub homepage_url: String,
    pub webhook_url: String,
    pub redirect_url: String,
    pub public: bool,
    pub permissions: Vec<ManifestPermission>,
    pub events: Vec<String>,
}

impl ManifestConfig {
    /// The FlexNetOS trusted-writer defaults (ADR-0008 §5): least-privilege permissions plus the
    /// webhook events the router consumes. `metadata:read` is mandatory for any App. Notably
    /// **no** `pull_requests` *approve* capability — the App posts a required status check and
    /// never bot-APPROVEs (#25439). The webhook secret is generated by GitHub at conversion time.
    pub fn trusted_writer(
        name: impl Into<String>,
        homepage_url: impl Into<String>,
        webhook_url: impl Into<String>,
        redirect_url: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            homepage_url: homepage_url.into(),
            webhook_url: webhook_url.into(),
            redirect_url: redirect_url.into(),
            public: false,
            permissions: vec![
                ManifestPermission::new("metadata", "read"),
                ManifestPermission::new("contents", "read"),
                ManifestPermission::new("checks", "write"),
                ManifestPermission::new("statuses", "write"),
                ManifestPermission::new("pull_requests", "write"),
            ],
            events: vec![
                "pull_request".into(),
                "push".into(),
                "check_suite".into(),
                "check_run".into(),
            ],
        }
    }
}

/// Build the manifest JSON GitHub expects in the `manifest` form field.
pub fn build_manifest(cfg: &ManifestConfig) -> Value {
    let mut perms = serde_json::Map::new();
    for p in &cfg.permissions {
        perms.insert(p.name.clone(), Value::String(p.access.clone()));
    }
    json!({
        "name": cfg.name,
        "url": cfg.homepage_url,
        "hook_attributes": { "url": cfg.webhook_url, "active": true },
        "redirect_url": cfg.redirect_url,
        "public": cfg.public,
        "default_permissions": Value::Object(perms),
        "default_events": cfg.events,
    })
}

/// The org-scoped App-creation URL the manifest form POSTs to. `state` is an opaque CSRF token
/// echoed back on the redirect; the caller must verify it round-trips unchanged.
pub fn org_create_url(org: &str, state: &str) -> String {
    format!("https://github.com/organizations/{org}/settings/apps/new?state={state}")
}

/// The successful response of `POST /app-manifests/{code}/conversions`. Holds secrets
/// (`pem`, `webhook_secret`) — deliberately **not** `Debug`, so it can't be logged by accident.
#[derive(Deserialize)]
pub struct Conversion {
    pub id: u64,
    #[serde(default)]
    pub slug: Option<String>,
    pub pem: String,
    pub webhook_secret: String,
    #[serde(default)]
    pub html_url: Option<String>,
    #[serde(default)]
    pub client_id: Option<String>,
}

/// Parse the conversion response JSON. Errors are message-only (never echo the body — it carries
/// the private key).
pub fn parse_conversion(json_str: &str) -> Result<Conversion, String> {
    serde_json::from_str(json_str)
        .map_err(|e| format!("could not parse manifest conversion response: {e}"))
}

/// The installation URL for the freshly-created App (prefers the slug-based path; falls back to
/// the App's `html_url`). Used by the approver's install phase.
pub fn install_url(conv: &Conversion) -> Option<String> {
    conv.slug
        .as_ref()
        .map(|s| format!("https://github.com/apps/{s}/installations/new"))
        .or_else(|| conv.html_url.clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trusted_writer_is_least_privilege_and_no_approve() {
        let cfg = ManifestConfig::trusted_writer(
            "flexnetos-trusted-writer",
            "https://example.invalid/home",
            "https://t.invalid/webhook",
            "https://example.invalid/callback",
        );
        // metadata:read is mandatory; checks/statuses/pull_requests are write; contents read-only.
        let find = |n: &str| {
            cfg.permissions
                .iter()
                .find(|p| p.name == n)
                .map(|p| p.access.as_str())
        };
        assert_eq!(find("metadata"), Some("read"));
        assert_eq!(find("contents"), Some("read"));
        assert_eq!(find("checks"), Some("write"));
        assert_eq!(find("statuses"), Some("write"));
        assert_eq!(find("pull_requests"), Some("write"));
        assert!(!cfg.public, "trusted writer is a private app");
        assert!(cfg.events.contains(&"pull_request".to_string()));
    }

    #[test]
    fn build_manifest_has_the_fields_github_requires() {
        let cfg = ManifestConfig::trusted_writer(
            "fxapp",
            "https://home.invalid",
            "https://tunnel.invalid/webhook",
            "https://localhost.invalid/callback",
        );
        let m = build_manifest(&cfg);
        assert_eq!(m["name"], "fxapp");
        assert_eq!(m["url"], "https://home.invalid");
        assert_eq!(
            m["hook_attributes"]["url"],
            "https://tunnel.invalid/webhook"
        );
        assert_eq!(m["hook_attributes"]["active"], true);
        assert_eq!(m["redirect_url"], "https://localhost.invalid/callback");
        assert_eq!(m["public"], false);
        // permissions land in default_permissions as a name→access object.
        assert_eq!(m["default_permissions"]["checks"], "write");
        assert_eq!(m["default_permissions"]["metadata"], "read");
        // events land in default_events as an array.
        assert!(m["default_events"]
            .as_array()
            .unwrap()
            .iter()
            .any(|e| e == "push"));
    }

    #[test]
    fn org_create_url_targets_the_org_endpoint() {
        assert_eq!(
            org_create_url("FlexNetOS", "abc123"),
            "https://github.com/organizations/FlexNetOS/settings/apps/new?state=abc123"
        );
    }

    #[test]
    fn parse_conversion_reads_id_pem_and_secret() {
        let body = r#"{
            "id": 456789,
            "slug": "flexnetos-trusted-writer",
            "pem": "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----\n",
            "webhook_secret": "s3cr3t-webhook",
            "html_url": "https://github.com/apps/flexnetos-trusted-writer",
            "client_id": "Iv1.abc123"
        }"#;
        let conv = parse_conversion(body).expect("valid conversion body");
        assert_eq!(conv.id, 456789);
        assert_eq!(conv.slug.as_deref(), Some("flexnetos-trusted-writer"));
        assert!(conv.pem.contains("BEGIN RSA PRIVATE KEY"));
        assert_eq!(conv.webhook_secret, "s3cr3t-webhook");
        assert_eq!(
            install_url(&conv).as_deref(),
            Some("https://github.com/apps/flexnetos-trusted-writer/installations/new")
        );
    }

    #[test]
    fn parse_conversion_rejects_garbage_without_echoing_it() {
        // `Conversion` has no Debug (it holds the private key), so match rather than unwrap_err.
        let err = match parse_conversion("not json") {
            Err(e) => e,
            Ok(_) => panic!("garbage must not parse as a conversion"),
        };
        assert!(err.contains("could not parse"));
        assert!(
            !err.contains("not json"),
            "must not echo the (secret-bearing) body"
        );
    }

    #[test]
    fn install_url_falls_back_to_html_url_when_no_slug() {
        let conv = parse_conversion(
            r#"{"id":1,"pem":"x","webhook_secret":"y","html_url":"https://github.com/apps/z"}"#,
        )
        .unwrap();
        assert_eq!(
            install_url(&conv).as_deref(),
            Some("https://github.com/apps/z")
        );
    }
}
